[package]
name = "argopt-impl"
version = "0.1.0"
authors = ["tanakh"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.10.2"
quote = "1.0.7"
syn = { version = "1.0.38", features = ["full", "extra-traits"] }
